-- Canonical Auth-backed schema for a fresh Supabase project.
-- Product images must live in Storage. Never store Base64/Data URLs in tables.

create extension if not exists pgcrypto;

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) between 1 and 80),
  description text not null default '' check (char_length(description) <= 500),
  image_url text,
  open_time time not null default '08:35',
  close_time time not null default '13:00',
  service_periods text[] not null default array['breakfast', 'lunch']::text[]
    check (
      cardinality(service_periods) > 0
      and service_periods <@ array['breakfast', 'lunch', 'afternoon_tea']::text[]
    ),
  status text not null default 'open' check (status in ('open', 'closed', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '' check (char_length(display_name) <= 80),
  grade text not null default '' check (grade in ('', 'high_1', 'high_2', 'high_3')),
  role text not null default 'customer' check (role in ('customer', 'store', 'admin')),
  store_id uuid references public.stores(id) on delete set null,
  status text not null default 'active' check (status in ('active', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((role = 'store' and store_id is not null) or role <> 'store')
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete restrict,
  name text not null check (char_length(trim(name)) between 1 and 100),
  category text not null default '其他' check (char_length(category) between 1 and 40),
  description text not null default '' check (char_length(description) <= 500),
  price numeric(12,2) not null check (price >= 0),
  image_path text check (
    image_path is null
    or (
      image_path !~ '^(data:|blob:|https?://)'
      and char_length(image_path) <= 500
    )
  ),
  -- Runtime signed URLs are generated by the client and are never persisted.
  image_url text check (image_url is null),
  status text not null default 'active' check (status in ('active', 'soldout', 'hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create sequence if not exists public.order_number_seq;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default (
    'ORD-' || to_char(now() at time zone 'Asia/Taipei', 'YYYYMMDD') || '-' ||
    lpad(nextval('public.order_number_seq')::text, 6, '0')
  ),
  customer_id uuid not null references auth.users(id) on delete restrict,
  customer_name text not null check (char_length(trim(customer_name)) between 1 and 80),
  customer_grade text not null default '' check (customer_grade in ('', 'high_1', 'high_2', 'high_3')),
  store_id uuid not null references public.stores(id) on delete restrict,
  pickup_time timestamptz not null,
  payment_method text not null check (payment_method in ('cash', 'campus')),
  total numeric(12,2) not null check (total >= 0),
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'preparing', 'ready', 'completed', 'rejected', 'cancelled')),
  idempotency_key uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (customer_id, idempotency_key)
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name_snapshot text not null,
  unit_price numeric(12,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity between 1 and 99),
  subtotal numeric(12,2) not null check (subtotal >= 0)
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  store_id uuid references public.stores(id) on delete cascade,
  order_id uuid references public.orders(id) on delete cascade,
  type text not null check (char_length(type) between 1 and 50),
  message text not null check (char_length(message) <= 500),
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  check (user_id is not null or store_id is not null)
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references auth.users(id) on delete cascade,
  store_id uuid not null references public.stores(id) on delete cascade,
  order_id uuid not null unique references public.orders(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text not null default '' check (char_length(comment) <= 500),
  hidden boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists products_store_status_idx on public.products(store_id, status);
create index if not exists orders_customer_created_idx on public.orders(customer_id, created_at desc);
create index if not exists orders_store_created_idx on public.orders(store_id, created_at desc);
create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);
create index if not exists notifications_store_created_idx on public.notifications(store_id, created_at desc);

revoke all on public.profiles, public.stores, public.products, public.orders,
  public.order_items, public.notifications, public.reviews from anon, authenticated;
grant select on public.stores, public.products to anon;
grant select on public.profiles, public.stores, public.products, public.orders,
  public.order_items, public.notifications, public.reviews to authenticated;
grant insert, update, delete on public.stores, public.products to authenticated;
grant update on public.profiles to authenticated;
grant insert, update on public.reviews to authenticated;

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at := now();
  return new;
end
$$;

drop trigger if exists stores_set_updated_at on public.stores;
create trigger stores_set_updated_at before update on public.stores
for each row execute function public.set_updated_at();
drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products
for each row execute function public.set_updated_at();
drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id, display_name, role)
  values (
    new.id,
    left(coalesce(new.raw_user_meta_data->>'display_name', ''), 80),
    'customer'
  )
  on conflict (id) do nothing;
  return new;
end
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

revoke execute on function public.set_updated_at() from public;
revoke execute on function public.handle_new_auth_user() from public;

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles
  where id = auth.uid() and status = 'active'
$$;

create or replace function public.current_store_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select store_id from public.profiles
  where id = auth.uid() and role = 'store' and status = 'active'
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_profile_role() = 'admin', false)
$$;

revoke execute on function public.current_profile_role() from public;
revoke execute on function public.current_store_id() from public;
revoke execute on function public.is_admin() from public;
grant execute on function public.current_profile_role() to anon, authenticated;
grant execute on function public.current_store_id() to anon, authenticated;
grant execute on function public.is_admin() to anon, authenticated;

alter table public.profiles enable row level security;
alter table public.stores enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.notifications enable row level security;
alter table public.reviews enable row level security;

drop policy if exists profiles_select_self_or_admin on public.profiles;
create policy profiles_select_self_or_admin on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());
drop policy if exists profiles_update_self_or_admin on public.profiles;
create policy profiles_update_self_or_admin on public.profiles for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists stores_public_read_open on public.stores;
create policy stores_public_read_open on public.stores for select to anon, authenticated
using (
  status = 'open'
  or public.is_admin()
  or id = public.current_store_id()
);
drop policy if exists stores_admin_insert on public.stores;
create policy stores_admin_insert on public.stores for insert to authenticated
with check (public.is_admin());
drop policy if exists stores_admin_update on public.stores;
create policy stores_admin_update on public.stores for update to authenticated
using (public.is_admin()) with check (public.is_admin());
drop policy if exists stores_admin_delete on public.stores;
create policy stores_admin_delete on public.stores for delete to authenticated
using (public.is_admin());

drop policy if exists products_read_catalog on public.products;
create policy products_read_catalog on public.products for select to anon, authenticated
using (
  public.is_admin()
  or store_id = public.current_store_id()
  or (
    status in ('active', 'soldout')
    and exists (select 1 from public.stores s where s.id = store_id and s.status = 'open')
  )
);
drop policy if exists products_store_insert on public.products;
create policy products_store_insert on public.products for insert to authenticated
with check (public.is_admin() or store_id = public.current_store_id());
drop policy if exists products_store_update on public.products;
create policy products_store_update on public.products for update to authenticated
using (public.is_admin() or store_id = public.current_store_id())
with check (public.is_admin() or store_id = public.current_store_id());
drop policy if exists products_store_delete on public.products;
create policy products_store_delete on public.products for delete to authenticated
using (public.is_admin() or store_id = public.current_store_id());

drop policy if exists orders_select_scoped on public.orders;
create policy orders_select_scoped on public.orders for select to authenticated
using (
  public.is_admin()
  or (customer_id = auth.uid() and public.current_profile_role() = 'customer')
  or store_id = public.current_store_id()
);
drop policy if exists order_items_select_scoped on public.order_items;
create policy order_items_select_scoped on public.order_items for select to authenticated
using (
  exists (
    select 1 from public.orders o
    where o.id = order_id
      and (
        public.is_admin()
        or (o.customer_id = auth.uid() and public.current_profile_role() = 'customer')
        or o.store_id = public.current_store_id()
      )
  )
);

drop policy if exists notifications_select_scoped on public.notifications;
create policy notifications_select_scoped on public.notifications for select to authenticated
using (
  public.is_admin()
  or (user_id = auth.uid() and public.current_profile_role() = 'customer')
  or store_id = public.current_store_id()
);
drop policy if exists notifications_update_scoped on public.notifications;

drop policy if exists reviews_read_scoped on public.reviews;
create policy reviews_read_scoped on public.reviews for select to authenticated
using (
  public.is_admin()
  or (customer_id = auth.uid() and public.current_profile_role() = 'customer')
  or (not hidden and store_id = public.current_store_id())
);
drop policy if exists reviews_customer_insert on public.reviews;
create policy reviews_customer_insert on public.reviews for insert to authenticated
with check (
  customer_id = auth.uid()
  and exists (
    select 1 from public.orders o
    where o.id = order_id and o.customer_id = auth.uid() and o.status = 'completed'
  )
);
drop policy if exists reviews_admin_update on public.reviews;
create policy reviews_admin_update on public.reviews for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create or replace function public.is_service_pickup_time(p_periods text[], p_time time)
returns boolean language sql immutable set search_path = public as $$
  select
    p_time between '08:35'::time and '08:45'::time
    or p_time between '09:30'::time and '09:40'::time
    or p_time between '10:25'::time and '10:35'::time
    or p_time between '11:20'::time and '11:30'::time
    or p_time between '12:15'::time and '13:00'::time
    or p_time between '17:15'::time and '17:30'::time
    or p_time between '18:15'::time and '18:25'::time
$$;

create or replace function public.update_my_profile(p_display_name text, p_grade text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_profile public.profiles%rowtype;
begin
  if auth.uid() is null then return jsonb_build_object('ok', false, 'code', 'bad_login'); end if;
  if char_length(trim(coalesce(p_display_name, ''))) not between 1 and 80 then
    return jsonb_build_object('ok', false, 'code', 'need_name');
  end if;
  if coalesce(p_grade, '') not in ('high_1', 'high_2', 'high_3') then
    return jsonb_build_object('ok', false, 'code', 'invalid_grade');
  end if;
  update public.profiles
  set display_name = trim(p_display_name), grade = p_grade
  where id = auth.uid() and role = 'customer' and status = 'active'
  returning * into v_profile;
  if not found then return jsonb_build_object('ok', false, 'code', 'bad_login'); end if;
  return jsonb_build_object('ok', true, 'profile', to_jsonb(v_profile));
end
$$;

create or replace function public.pickup_is_within_order_window(p_pickup timestamptz)
returns boolean
language sql
stable
set search_path = public
as $$
  select
    p_pickup >= now() + interval '15 minutes'
    and (p_pickup at time zone 'Asia/Taipei')::date
        <= (timezone('Asia/Taipei', now()))::date + 1
$$;

create or replace function public.create_order(
  p_store_id uuid,
  p_customer_name text,
  p_pickup_time timestamptz,
  p_payment_method text,
  p_items jsonb,
  p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_store public.stores%rowtype;
  v_order public.orders%rowtype;
  v_existing public.orders%rowtype;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
  v_total numeric(12,2) := 0;
begin
  if auth.uid() is null then
    return jsonb_build_object('ok', false, 'code', 'bad_login');
  end if;
  select * into v_profile from public.profiles
  where id = auth.uid() and role = 'customer' and status = 'active';
  if not found then return jsonb_build_object('ok', false, 'code', 'bad_login'); end if;
  if char_length(trim(coalesce(p_customer_name, ''))) not between 1 and 80 then
    return jsonb_build_object('ok', false, 'code', 'need_name');
  end if;

  select * into v_existing from public.orders
  where customer_id = auth.uid() and idempotency_key = p_idempotency_key;
  if found then
    return jsonb_build_object('ok', true, 'duplicate', true, 'order', to_jsonb(v_existing));
  end if;

  select * into v_store from public.stores where id = p_store_id and status = 'open' for update;
  if not found then return jsonb_build_object('ok', false, 'code', 'store_closed'); end if;
  if not public.pickup_is_within_order_window(p_pickup_time)
     or extract(minute from p_pickup_time)::integer % 5 <> 0
     or extract(second from p_pickup_time) <> 0
     or not public.is_service_pickup_time(
       v_store.service_periods,
       (p_pickup_time at time zone 'Asia/Taipei')::time
     ) then
    return jsonb_build_object('ok', false, 'code', 'invalid_pickup');
  end if;
  if p_payment_method not in ('cash', 'campus') then
    return jsonb_build_object('ok', false, 'code', 'invalid_payment');
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    return jsonb_build_object('ok', false, 'code', 'invalid_items');
  end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    begin
      v_qty := (v_item->>'quantity')::integer;
    exception when others then
      return jsonb_build_object('ok', false, 'code', 'invalid_items');
    end;
    select * into v_product from public.products
    where id = (v_item->>'product_id')::uuid
      and store_id = p_store_id and status = 'active'
    for update;
    if not found or v_qty not between 1 and 99 then
      return jsonb_build_object('ok', false, 'code', 'invalid_items');
    end if;
    v_total := v_total + (v_product.price * v_qty);
  end loop;

  update public.profiles
  set display_name = trim(p_customer_name)
  where id = auth.uid();

  insert into public.orders(
    customer_id, customer_name, customer_grade, store_id, pickup_time,
    payment_method, total, status, idempotency_key
  )
  values (
    auth.uid(), trim(p_customer_name), v_profile.grade, p_store_id, p_pickup_time,
    p_payment_method, v_total, 'pending', p_idempotency_key
  )
  returning * into v_order;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := (v_item->>'quantity')::integer;
    select * into v_product from public.products where id = (v_item->>'product_id')::uuid;
    insert into public.order_items(
      order_id, product_id, product_name_snapshot, unit_price, quantity, subtotal
    )
    values (
      v_order.id, v_product.id, v_product.name, v_product.price, v_qty, v_product.price * v_qty
    );
  end loop;

  insert into public.notifications(store_id, order_id, type, message)
  values (p_store_id, v_order.id, 'new_order', '新訂單 ' || v_order.order_number);

  return jsonb_build_object('ok', true, 'order', to_jsonb(v_order));
exception
  when unique_violation then
    select * into v_existing from public.orders
    where customer_id = auth.uid() and idempotency_key = p_idempotency_key;
    return jsonb_build_object('ok', true, 'duplicate', true, 'order', to_jsonb(v_existing));
  when invalid_text_representation then
    return jsonb_build_object('ok', false, 'code', 'invalid_items');
end
$$;

create or replace function public.update_order_status(p_order_id uuid, p_next_status text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_allowed boolean;
begin
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then return jsonb_build_object('ok', false, 'code', 'no_order'); end if;
  if not public.is_admin() and v_order.store_id is distinct from public.current_store_id() then
    return jsonb_build_object('ok', false, 'code', 'not_store');
  end if;
  v_allowed :=
    (v_order.status = 'pending' and p_next_status in ('accepted', 'rejected'))
    or (v_order.status = 'accepted' and p_next_status = 'preparing')
    or (v_order.status = 'preparing' and p_next_status = 'ready')
    or (v_order.status = 'ready' and p_next_status = 'completed');
  if not v_allowed then return jsonb_build_object('ok', false, 'code', 'invalid_status'); end if;

  update public.orders set status = p_next_status where id = p_order_id returning * into v_order;
  insert into public.notifications(user_id, store_id, order_id, type, message)
  values (
    v_order.customer_id, v_order.store_id, v_order.id, 'order_status',
    v_order.order_number || '：' || p_next_status
  );
  return jsonb_build_object('ok', true, 'order', to_jsonb(v_order));
end
$$;

create or replace function public.cancel_order(p_order_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_staff boolean;
begin
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then return jsonb_build_object('ok', false, 'code', 'no_order'); end if;
  v_staff := public.is_admin() or v_order.store_id = public.current_store_id();
  if not v_staff and v_order.customer_id <> auth.uid() then
    return jsonb_build_object('ok', false, 'code', 'cannot_cancel');
  end if;
  if (not v_staff and v_order.status <> 'pending')
     or (v_staff and v_order.status not in ('pending', 'accepted', 'preparing')) then
    return jsonb_build_object('ok', false, 'code', 'cannot_cancel');
  end if;
  update public.orders set status = 'cancelled' where id = p_order_id returning * into v_order;
  return jsonb_build_object('ok', true, 'order', to_jsonb(v_order));
end
$$;

create or replace function public.delete_or_hide_product(p_product_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product public.products%rowtype;
  v_has_orders boolean;
begin
  select * into v_product from public.products where id = p_product_id for update;
  if not found then return jsonb_build_object('ok', false, 'code', 'no_product'); end if;
  if not public.is_admin() and v_product.store_id is distinct from public.current_store_id() then
    return jsonb_build_object('ok', false, 'code', 'not_store');
  end if;
  select exists(select 1 from public.order_items where product_id = p_product_id) into v_has_orders;
  if v_has_orders then
    update public.products set status = 'hidden' where id = p_product_id returning * into v_product;
    return jsonb_build_object('ok', true, 'hidden', true, 'product', to_jsonb(v_product));
  end if;
  delete from public.products where id = p_product_id;
  return jsonb_build_object('ok', true, 'deleted', true, 'image_path', v_product.image_path);
end
$$;

create or replace function public.mark_notification_read(p_notification_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.notifications
  set is_read = true
  where id = p_notification_id
    and (
      public.is_admin()
      or user_id = auth.uid()
      or store_id = public.current_store_id()
    );
  if not found then return jsonb_build_object('ok', false, 'code', 'not_found'); end if;
  return jsonb_build_object('ok', true);
end
$$;

revoke execute on function public.is_service_pickup_time(text[], time) from public;
revoke execute on function public.pickup_is_within_order_window(timestamptz) from public;
revoke execute on function public.update_my_profile(text, text) from public;
revoke execute on function public.create_order(uuid, text, timestamptz, text, jsonb, uuid) from public;
revoke execute on function public.update_order_status(uuid, text) from public;
revoke execute on function public.cancel_order(uuid) from public;
revoke execute on function public.delete_or_hide_product(uuid) from public;
create or replace function public.provision_email_user(
  p_email text,
  p_password text,
  p_display_name text
)
returns uuid
language plpgsql
security definer
set search_path = public, auth, extensions
as $$
declare
  v_id uuid := gen_random_uuid();
  v_email text := lower(trim(p_email));
begin
  insert into auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
    confirmation_token, recovery_token, email_change_token_new, email_change
  )
  values (
    '00000000-0000-0000-0000-000000000000',
    v_id, 'authenticated', 'authenticated', v_email,
    crypt(p_password, gen_salt('bf')), now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    jsonb_build_object('display_name', left(coalesce(p_display_name, ''), 80)),
    now(), now(), '', '', '', ''
  );

  insert into auth.identities (
    id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
  )
  values (
    gen_random_uuid(), v_id,
    jsonb_build_object('sub', v_id::text, 'email', v_email),
    'email', v_id::text, now(), now(), now()
  );

  return v_id;
end
$$;

create or replace function public.create_guest_login()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid := gen_random_uuid();
  v_email text := 'guest_' || replace(v_id::text, '-', '') || '@campus-order.test';
  v_password text := replace(gen_random_uuid()::text, '-', '') || 'Aa1';
begin
  perform public.provision_email_user(v_email, v_password, '');
  return jsonb_build_object('ok', true, 'email', v_email, 'password', v_password);
end
$$;

create or replace function public.create_store_account(
  p_store_id uuid,
  p_username text,
  p_password text,
  p_display_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_email text;
  v_user_id uuid;
begin
  if not public.is_admin() then
    return jsonb_build_object('ok', false, 'code', 'not_admin');
  end if;
  if not exists (select 1 from public.stores where id = p_store_id) then
    return jsonb_build_object('ok', false, 'code', 'no_store');
  end if;
  v_email := lower(trim(coalesce(p_username, '')));
  if v_email not like '%@%' then
    v_email := v_email || '@campus-order.test';
  end if;
  if char_length(trim(coalesce(p_username, ''))) < 1 or char_length(coalesce(p_password, '')) < 4 then
    return jsonb_build_object('ok', false, 'code', 'invalid_account');
  end if;
  if exists (select 1 from auth.users where email = v_email) then
    return jsonb_build_object('ok', false, 'code', 'username_taken');
  end if;

  v_user_id := public.provision_email_user(
    v_email, p_password, coalesce(nullif(trim(p_display_name), ''), trim(p_username))
  );
  update public.profiles
  set role = 'store',
      store_id = p_store_id,
      display_name = coalesce(nullif(trim(p_display_name), ''), trim(p_username)),
      status = 'active'
  where id = v_user_id;

  return jsonb_build_object('ok', true, 'user_id', v_user_id, 'username', trim(p_username));
end
$$;

create or replace function public.reset_store_password(p_store_id uuid, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, extensions
as $$
declare
  v_user_id uuid;
begin
  if not public.is_admin() then
    return jsonb_build_object('ok', false, 'code', 'not_admin');
  end if;
  if char_length(coalesce(p_password, '')) < 4 then
    return jsonb_build_object('ok', false, 'code', 'password_too_short');
  end if;
  select id into v_user_id
  from public.profiles
  where store_id = p_store_id and role = 'store'
  limit 1;
  if v_user_id is null then
    return jsonb_build_object('ok', false, 'code', 'no_user');
  end if;
  update auth.users
  set encrypted_password = crypt(p_password, gen_salt('bf')),
      email_confirmed_at = coalesce(email_confirmed_at, now())
  where id = v_user_id;
  return jsonb_build_object('ok', true);
end
$$;

revoke execute on function public.mark_notification_read(uuid) from public;
revoke all on function public.provision_email_user(text, text, text) from public, anon, authenticated;
revoke execute on function public.create_guest_login() from public;
revoke execute on function public.create_store_account(uuid, text, text, text) from public;
revoke execute on function public.reset_store_password(uuid, text) from public;
grant execute on function public.create_order(uuid, text, timestamptz, text, jsonb, uuid) to authenticated;
grant execute on function public.create_guest_login() to anon, authenticated;
grant execute on function public.create_store_account(uuid, text, text, text) to authenticated;
grant execute on function public.reset_store_password(uuid, text) to authenticated;
grant execute on function public.update_my_profile(text, text) to authenticated;
grant execute on function public.update_order_status(uuid, text) to authenticated;
grant execute on function public.cancel_order(uuid) to authenticated;
grant execute on function public.delete_or_hide_product(uuid) to authenticated;
grant execute on function public.mark_notification_read(uuid) to authenticated;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images', 'product-images', false, 1048576,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists product_images_read_published on storage.objects;
create policy product_images_read_published on storage.objects for select to anon, authenticated
using (
  bucket_id = 'product-images'
  and (
    public.is_admin()
    or (storage.foldername(storage.objects.name))[1] = public.current_store_id()::text
    or exists (
      select 1 from public.products p
      join public.stores s on s.id = p.store_id
      where p.image_path = storage.objects.name
        and p.status in ('active', 'soldout')
        and s.status = 'open'
    )
  )
);
drop policy if exists product_images_insert_owner on storage.objects;
create policy product_images_insert_owner on storage.objects for insert to authenticated
with check (
  bucket_id = 'product-images'
  and (
    public.is_admin()
    or (storage.foldername(storage.objects.name))[1] = public.current_store_id()::text
  )
);
drop policy if exists product_images_update_owner on storage.objects;
create policy product_images_update_owner on storage.objects for update to authenticated
using (
  bucket_id = 'product-images'
  and (
    public.is_admin()
    or (storage.foldername(storage.objects.name))[1] = public.current_store_id()::text
  )
)
with check (
  bucket_id = 'product-images'
  and (
    public.is_admin()
    or (storage.foldername(storage.objects.name))[1] = public.current_store_id()::text
  )
);
drop policy if exists product_images_delete_owner on storage.objects;
create policy product_images_delete_owner on storage.objects for delete to authenticated
using (
  bucket_id = 'product-images'
  and (
    public.is_admin()
    or (storage.foldername(storage.objects.name))[1] = public.current_store_id()::text
  )
);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notifications'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end
$$;
